### ISSUE TITLE
Problem building mock_network example

### ISSUE THREAD

**Issue by welchons** [atilaneves/premock#1]
I tried to build the mock_network example using the command below.  The -I../.. is for the premock.hpp file.  Am I doing something wrong?
Thanks.

  mocks git:(master) pwd
/home/welchons/premock/example/cpp/mocks

➜  mocks git:(master) gcc mock_network.cpp -include mock_network.h -I. -I../../.. -std=c++14 
In file included from mock_network.hpp:4:0,
                 from mock_network.cpp:1:
../../../premock.hpp:502:58: error: ‘mock_ut_send’ was not declared in this scope
 #define MOCK_STORAGE_DEFAULT(func) thread_local decltype(mock_##func) mock_##func = func
                                                          ^
../../../premock.hpp:594:5: note: in expansion of macro ‘MOCK_STORAGE_DEFAULT’
     MOCK_STORAGE_DEFAULT(func)
     ^
mock_network.cpp:3:12: note: in expansion of macro ‘IMPL_MOCK_DEFAULT’
 extern "C" IMPL_MOCK_DEFAULT(4, send);
            ^
../../../premock.hpp:502:58: error: ‘mock_ut_send’ was not declared in this scope
 #define MOCK_STORAGE_DEFAULT(func) thread_local decltype(mock_##func) mock_##func = func
                                                          ^
../../../premock.hpp:594:5: note: in expansion of macro ‘MOCK_STORAGE_DEFAULT’
     MOCK_STORAGE_DEFAULT(func)
     ^
mock_network.cpp:3:12: note: in expansion of macro ‘IMPL_MOCK_DEFAULT’
 extern "C" IMPL_MOCK_DEFAULT(4, send);
            ^
./mock_network.h:4:14: error: invalid conversion from ‘FunctionTraits<long int (*)(int, const void*, long unsigned int, int)>::ReturnType (_)(FunctionTraits<long int (_)(int, const void_, long unsigned int, int)>::Arg<0>::Type, FunctionTraits<long int (_)(int, const void_, long unsigned int, int)>::Arg<1>::Type, FunctionTraits<long int (_)(int, const void_, long unsigned int, int)>::Arg<2>::Type, FunctionTraits<long int (_)(int, const void_, long unsigned int, int)>::Arg<3>::Type) {aka long int (_)(int, const void*, long unsigned int, int)}’ to ‘int’ [-fpermissive]
 #define send ut_send
              ^
../../../premock.hpp:502:85: note: in definition of macro ‘MOCK_STORAGE_DEFAULT’
 #define MOCK_STORAGE_DEFAULT(func) thread_local decltype(mock_##func) mock_##func = func
                                                                                     ^
mock_network.cpp:3:12: note: in expansion of macro ‘IMPL_MOCK_DEFAULT’
 extern "C" IMPL_MOCK_DEFAULT(4, send);
            ^
mock_network.cpp:3:33: note: in expansion of macro ‘send’
 extern "C" IMPL_MOCK_DEFAULT(4, send);

**Comment by atilaneves** [comment]
You're missing a few compiler flags. There's a Makefile, a ninja file and a Tupfile in the top directory - just pick a build system and type `make`, `ninja` or `tup` accordingly -they'll all build the example executable.

**Comment by welchons** [comment]
Thanks for responding to me with the advice.  Sorry it took me so long to get back to you.  I should have tried building with the Makefile before I bothered you.  After looking at the output of the build, I think my mistake was that I was compiling _all_ the files with the “-include mock_network.h” compiler flag, when only the file that actually makes the call to send(), prod.c in this case, needed to be compiled with that flag.

Thanks again.

Dave

**Comment by welchons** [comment]
Dear Mr. Neves,

I this is not an acceptable method of contacting you, just let me know.  If I should open another issue, just let me know.
1. ```
    I am trying to “REPLACE” two functions in a calling-function-to-be-tested.  It seems that if I comment out either one of the REPLACE statements, it builds.  But with both REPLACE statements, it does not build.   Is premock only meant to REPLACE one function at a time in a function-to-be-tested?
   ```
2. ```
    I am having trouble getting MOCK to work on a function with no parameters (nl_socket_alloc, to be specific).   Is the premock MOCK statement only meant to mock functions with parameters?
   ```

Thanks,

Dave Welchons
