### ISSUE TITLE
Problem building test.cpp with 2 REPLACEs in same scope

### ISSUE THREAD

**Issue by welchons** [atilaneves/premock#2]
I would like to REPLACE several functions in a to-be-tested function, such as where a sequence of functions are called within another functions.  When I add a second REPLACE in the same scope in the example program test.cpp, build errors occur as shown below.

➜  premock git:(master) ✗ pwd
/home/welchons/premock
➜  premock git:(master) ✗ make
clang++ -Wall -Werror -Wextra -g -std=c++14 -I. -Iexample/cpp/test -Iexample/src -Iexample/deps -Iexample/cpp/mocks -MMD -MT objs/example_cpp.objs/example/cpp/test/test.o -MF objs/example_cpp.objs/example/cpp/test/test.o.dep -o objs/example_cpp.objs/example/cpp/test/test.o -c example/cpp/test/test.cpp
example/cpp/test/test.cpp:41:9: error: redefinition of '_'
        REPLACE(other_one, [](int i) { return 4 \* i; });
        ^
./premock.hpp:149:36: note: expanded from macro 'REPLACE'
# define REPLACE(func, lambda) auto _ = mockScope(mock_##func, lambda)

```
                               ^
```

example/cpp/test/test.cpp:37:9: note: previous definition is here
        REPLACE(other_zero, []() { return 3; });
        ^
./premock.hpp:149:36: note: expanded from macro 'REPLACE'
# define REPLACE(func, lambda) auto _ = mockScope(mock_##func, lambda)

```
                               ^
```

1 error generated.
Makefile:9: recipe for target 'objs/example_cpp.objs/example/cpp/test/test.o' failed
make: **\* [objs/example_cpp.objs/example/cpp/test/test.o] Error 1

The code for test.cpp is shown below with 2 REPLACE's in the second scope containing REPLACE.

`#include "mocks.hpp"
# include "prod.h"
# include "cpp_prod.hpp"
# include <iostream>
# include <string>
# include <stdexcept>
# include <functional>

using namespace std;

template<typename A, typename E>
static void assertEqual(A&& actual, E&& expected) {
    if(actual != expected)
        throw runtime_error("\nExpected: " + to_string(expected) +
                            "\nActual:   " + to_string(actual));
}

int main() {
    {
        REPLACE(send, [](auto...) { return 7; });
        assertEqual(prod_send(0), 7);
    }

```
// out of scope, send reverts to the "real" implementation
// which will return -1 since 0 isn't a valid socket file
// descriptor
assertEqual(prod_send(0), -1);

{
    auto m = MOCK(send);
    prod_send(3);
    m.expectCalled().withValues(3, nullptr, 0, 0);
}
{
    REPLACE(other_zero, []() { return 3; });
    assertEqual(prod_zero(), 3);

    // Add 2nd REPLACE in this scope
    REPLACE(other_one, [](int i) { return 4 * i; });
    assertEqual(prod_one(8), 36);
}
{
    REPLACE(other_one, [](int i) { return 4 * i; });
    assertEqual(prod_one(8), 36);
}
{
    REPLACE(other_two, [](int i, int j) { return i + j + 1; });
    assertEqual(prod_two(3, 4), 8);
}
{
    REPLACE(other_three, [](double, int j, const char*){
        if(j == 2) throw runtime_error("oh noes");
    });
    prod_three(0, 1, nullptr);
    try {
        prod_three(0, 0, nullptr); //should throw
        throw logic_error("oops"); //should never get here
    } catch(const runtime_error&) { }
}

{
    auto m = MOCK(other_two);
    m.returnValue(5); //prod_two should call mock_other_two and return 5 no matter what
    assertEqual(prod_two(99, 999), 5);
    m.expectCalled().withValues(98, 1000);
}

{
    auto m = MOCK(other_two);
    m.returnValue(11, 22, 33);
    assertEqual(prod_two(99, 999), 11);
    assertEqual(prod_two(9, 10), 22);
    assertEqual(prod_two(5, 5), 33);
    m.expectCalled(3).withValues(4, 6);
}

{
    auto mock1 = MOCK(other_one); //because we can
    auto mock2 = MOCK(other_two);
    mock2.returnValue(11, 22, 33);
    assertEqual(prod_two(99, 999), 11);
    assertEqual(prod_two(9, 10), 22);
    assertEqual(prod_two(5, 5), 33);
    mock2.expectCalled(3).withValues({make_tuple(98, 1000), make_tuple(8, 11), make_tuple(4, 6)});
}

{
    //C++ function mocking
    auto m = MOCK(twice);
    prod_twice(2, 3);
    m.expectCalled().withValues(5);
}


cout << "Ok C++ Example" << endl;
```

}
`

**Comment by atilaneves** [comment]
That's not going to work because `REPLACE` introduces a variable called `_`. This is mostly because I was lazy, it's possible to trick the compiler into producing more or less unique variable names.

**Comment by welchons** [comment]
Thanks!

Dave
